//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageUploadDenemesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int ID { get; set; }
        public string Adi { get; set; }
        public int KategoriId { get; set; }
        public string Resim { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
